### ISSUE TITLE
Error message persists after fix/save

### ISSUE THREAD

**Issue by capdevc** [microsoft/vscode-mypy#119]
mypy: 1.5.0
extension: v2023.3.12231010
vscode: Version: 1.82.0-insider Commit: 2d9cc42045edf3458acbddf3d645bba993f82696

If I have a type error:

```
a: int = "asd"

Error:
Incompatible types in assignment (expression has type "str", variable has type "int")
```

And then I delete or fix the line with the error and save, mypy runs and produces no error, but the error diagnostic persists in vs-code:

<img width="667" alt="image" src="https://github.com/microsoft/vscode-mypy/assets/1211248/cbcb460a-86c9-4c2d-be03-00f336bd149c">

You can see that the blank line has the tilde with the type error still. This persists until something triggers another error. It looks like the "no error" output isn't being parsed correctly or an update isn't being sent to vs-code.

Originally raised by @cpnielsen  in #115

**Comment by samskiter** [comment]
My observation is that this is happening when I clear the *last* error in my workspace. If I introduce a new error, the one I just fixes disappears and the problem moves onto the new error... If I restart the extension, the issue resolves.

**Comment by cpnielsen** [comment]
The underlying issue is that if mypy returns no errors for a file, the current code does not emit "empty diagnostics" for the file to clear out any existing errors. The issue is identical if you have 5 errors and clear them all out in 1 go, then save/run mypy and all 5 remain because the file diagnostics are not updated.

Offending line: https://github.com/microsoft/vscode-mypy/blob/main/bundled/tool/lsp_server.py#L116C12-L116C12

My suggestion (I am swamped and do not have time to address it this week):
- Check if `result and result.exit_code is 0`
- If the file in question is not part of the returned result (in this block: https://github.com/microsoft/vscode-mypy/blob/main/bundled/tool/lsp_server.py#L117-L138), run `LSP_SERVER.publish_diagnostics(document.uri, [])`.

It becomes more tricky with workspace reportingScope, as you'd have to investigate all documents with prior errors and clear them out, which requires some state management (I am not _that_ familiar with LSP_SERVER internals).

**Comment by samskiter** [comment]
@cpnielsen  https://github.com/microsoft/vscode-mypy/pull/123 I had a go at a fix

**Comment by samskiter** [comment]
Ooops just saw you commented at the same time @cpnielsen - I think I've done a more 'thorough' solution that works for both `reportingScope`s in my PR. I'm not using the result_code but instead looking for whether the diagnostic results contain anything for the filepath, and if not submitting an empty array as you suggest (`LSP_SERVER.publish_diagnostics(document.uri, [])`).

This is how similar extensions, like pylint, implicitly work (as they are only run on a file at a time, they always construct an empty array):
https://github.com/microsoft/vscode-pylint/blob/main/bundled/tool/lsp_server.py#L167

I unfortunately don't know how to test if my solution works - do you have time to do that please? or can you point me to any quick instructions to do it myself?

**Comment by cpnielsen** [comment]
There's an extensive guide on testing VS Code extensions here: https://code.visualstudio.com/api/working-with-extensions/testing-extension. You can also build the extension locally and try installing that version to see if that works.

You should also check out the contributor guide here: https://github.com/microsoft/vscode-mypy/wiki/Contributing-Guide#testing

**Comment by karthiknadig** [comment]
@samskiter I have responded to your PR. I have also included more details on how debug the python code in the contributor guide as well.
