### ISSUE TITLE
[Bug] Does one analysis at start, and never re analyses the file unless VSCode is closed and reopened

### ISSUE THREAD

**Issue by JDurSyn** [microsoft/vscode-mypy#132]
Installed the mypy release version v2023.2.0

Reloaded VSCode after install

It correctly linted my file at the start (16 problems)

I modified my file, try adding an additional problem

Then the problem window is empty

Tried to save the file, close & open the file, nothing works

BUT closing VSCode & Re-opening it works, the file is linted again

If I make a new modification, again, "No problem" is shown and no new analysis results are displayed

It is on Windows but using a remote Linux through SSH

Settings are : 

    "mypy-type-checker.interpreter": [
        ".venv/bin/python"
    ],
    "mypy-type-checker.args": [
        "--explicit-package-bases"
    ],

**Comment by karthiknadig** [comment]
@JDurSyn This is likely due to an issue with `dmypy` itself. See here https://github.com/microsoft/vscode-mypy/issues/88

You can force the extension to use `mypy` as suggested in the comment here: https://github.com/microsoft/vscode-mypy/issues/88#issuecomment-1636167871

I plan on adding a setting to make it easier to switch between `mypy` or `dmypy`. So closing this in favor of : https://github.com/microsoft/vscode-mypy/issues/115

**Comment by karthiknadig** [comment]
@JDurSyn You should be able to see the Output > Mypy Type Checker logs to see what is being reports by the tool itself.

**Comment by JDurSyn** [comment]
@karthiknadig Thanks you for the suggestion, I will try this now

**Comment by JDurSyn** [comment]
Ok thanks @karthiknadig it works fine now. Left a 5 star reviews on your extension page, great extension !
