### ISSUE TITLE
Remove default arguments

### ISSUE THREAD

**Issue by jokance** [microsoft/vscode-mypy#210]
I dont know why mypy add these command line arguments, and I cant remove them:

```shell
c:\Users\myname\.virtualenvs\XXX\Scripts\python.exe -m mypy --no-color-output --no-error-summary --show-absolute-path --show-column-numbers --show-error-codes --no-pretty --config-file=f:\Projects/pyproject.toml --show-error-end 
```
I only add --config-file in settings.json:
```ini
"mypy-type-checker.args": [
    "--config-file=${workspaceFolder}/pyproject.toml"
]
```

Windows: 10 21H2
VSCode: 1.84.0
Mypy Type Checker: v2023.6.0

**Comment by karthiknadig** [comment]
This is by design. Those CLI arguments are needed by the extension to work. We need to parse the output to show them in the problems view. This output is entirely consumed by the extension, those arguments to make it consistent and easier to parse the output.

If you want to run `mypy` as needed, you can set-up tasks using task.json, and trigger them as needed.

**Comment by jokance** [comment]
@karthiknadig Got it!
