### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by blackwood-nomad** [microsoft/vscode-mypy#280]
Would it be possible to do a new release that includes the the updates to the pygls package? https://github.com/microsoft/vscode-mypy/pull/238
I think that will fix the `ImportError: cannot import name 'Buffer' from 'typing_extensions'` issues with the mypy extension when running on older versions of python.

**Comment by karthiknadig** [comment]
Please try this pre-release build: 2023.9.10221010

**Comment by blackwood-nomad** [comment]
That did it, thanks!

**Comment by ShadowLNC** [comment]
@karthiknadig I am finding VSCode still prefers to install `v2023.6.0` and I'm also having some issues that seem to be fixed in the pre-release - is it possible to ship a production release please?

---

Specifically when I get this warning `pyproject.toml: [mypy]: enable_error_code: Invalid error code(s): ...` due to an outdated bundled `mypy` version, then the rest of my `enabled_error_code` options are ignored, in this case `ignore-without-type`.

If I remove the "invalid" (new) error codes, then I see the `ignore-without-type` error in the VSCode "Mypy Type Checker" output, but it does not appear in the "problems" tab or in the file itself, and neither does a `error: Unused "type: ignore" comment  [unused-ignore]` directive if I deliberately put a non-matching code instead.
