### ISSUE TITLE
Whats the difference between this Extension and the microsoft pylance?

### ISSUE THREAD

**Issue by shanaor** [microsoft/vscode-mypy#333]
and does the pylance check the type across all files including from the imports ?

**Comment by karthiknadig** [comment]
This extension is based on `mypy` type checker. `mypy` is a Python based linter that does type checking. Since it is written in Python it requires Python to run. This extension only supports linting and type checking.

Pylance uses a different type checker, in addition it also provides completions, hover, go definition , etc. it can run without Python.

**Comment by shanaor** [comment]
so in the end pylance does the same as mypy and more? 

and does ny of them do typechecking inrelation to imported files\functions?

**Comment by karthiknadig** [comment]
> so in the end pylance does the same as mypy and more?

Yes, Pylance has more features.

> and does ny of them do typechecking inrelation to imported files\functions?

Both can do this.

**Comment by eleanorjboyd** [comment]
seems like the answer is resolved- comment if not and I can re-open. Thanks!
